### ISSUE TITLE
502: Bad Gateway

### ISSUE THREAD

**Issue by chpins** [hassio-addons/addon-phpmyadmin#113]
# Problem/Motivation

In HASS.IO, addon is started, log is empty and when try to acces I have : 502: Bad Gateway  message.

How to debug this problem ?

**Comment by frenck** [comment]
Anything in the addon logs?

**Comment by p0l0** [comment]
I had the same issue. The last message in the log was:

```
[14:19:10] INFO: Creating database for phpMyAdmin
```

At the MariaDB addon I saw, that the connection was aborted for the "service" user due to a timeout, after restarting the MariaDB addon, the Phpmyadmin addon was able to startup successfully:

```
[cont-init.d] phpmyadmin.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[14:28:12] INFO: Starting PHP-FPM...
[14:28:13] INFO: Starting NGinx....
```

What is strange, i tried before restarting 2-3 times the phpmyadmin addon, and it was stuck at the same point, the only thing which solved the issue, was restarting the MariaDB addon.
