### ISSUE TITLE
How to change server to connect?

### ISSUE THREAD

**Issue by saspol** [hassio-addons/addon-phpmyadmin#43]
Hello,
Please add such options to add-on.

**Comment by sinclairpaul** [comment]
You can't, it is purely designed to manage the local Maria DB addon as per the description in the documentation.

**Comment by saspol** [comment]
> You can't, it is purely designed to manage the local Maria DB addon as per the description in the documentation.

This wrong behaviour must be fixed. Stock phpmyadmin also allow control which server to connect.

**Comment by frenck** [comment]
> Stock phpmyadmin also allow control which server to connect.

This is not stock phpMyAdmin, this add-on is designed to connect with the database in this eco system.

It will not be added and we don't consider it wrong behavior. Feel free to build your own add-ons.

**Comment by saspol** [comment]
There is no any limit from hassio, how many databases have in this "ecosystem". You put in this add-on ablolutely artificial limitations.

**Comment by frenck** [comment]
Please note, "hassio" does not exists as a term anymore and its ambiguous as well.

> how many databases have in this "ecosystem"

Depends if you mean database server, or databases on that server, either way, compatible servers can announce themselves via the Supervisor discovery. This add-on will pick them up in that case.

> You put in this add-on ablolutely artificial limitations.

Sorry to hear you feel that way. Every option you add may add flexibility but also adds maintenance (in terms of code and support). Since I'm the one that is responsible for that, I decide on how much of that I want to provide. Additionally, more options cause more confusion with lesser knowledgeable users. I aim for a click, go and should be working experience.

Honestly, IMHO, if you need an add-on to manage external databases... you are using the wrong installation type to being with.

Lucky this is open source. Feel free to build your own and do better 👍
